// src/config/componentRegistry.js
export const componentRegistry = [
  {
    id: 'header',
    name: 'Location Header',
    description: 'City name and region display',
    defaultVisible: false,
    category: 'info',
    required: true,
  },
  {
    id: 'hero',
    name: 'Current Weather Snapshot',
    description: 'Main temperature and conditions display',
    defaultVisible: true,
    category: 'weather',
    required: false,
  },
  {
    id: 'weather-watch',
    name: 'Weather Watch',
    description: 'Weather like a wristwatch dial',
    defaultVisible: true,
    category: 'weather',
    required: false,
  },
  {
    id: 'daysnapshot-today',
    name: 'Today Essentials',
    description: 'Quick current weather view',
    defaultVisible: true,
    category: 'simpler',
    required: false,
  },
  {
    id: 'daysnapshot-tomorrow',
    name: 'Tomorrow Essentials',
    description: 'Quick future weather view',
    defaultVisible: true,
    category: 'simpler',
    required: false,
  },
  {
    id: 'stats',
    name: 'Current Weather Conditions',
    description: 'Wind, humidity, pressure, and other stats',
    defaultVisible: true,
    category: 'weather',
    required: false,
  },
  {
    id: 'wind',
    name: 'Wind Graphic',
    description: 'Wind conditions visualized',
    defaultVisible: true,
    category: 'weather',
    required: false,
  },
  {
    id: 'dewpoint',
    name: 'Dew Point Comfort',
    description: 'How sticky does it feel',
    defaultVisible: true,
    category: 'weather',
    required: false,
  },
  {
    id: 'pressure-trends',
    name: 'Pressure Trends',
    description: 'Storm approaching? or all calm ...',
    defaultVisible: true,
    category: 'weather',
    required: false,
  },
  {
    id: 'hourly',
    name: 'Hourly Forecast',
    description: '24-hour temperature and precipitation chart',
    defaultVisible: true,
    category: 'forecast',
    required: false,
  },
  {
    id: 'hourlyprecip',
    name: 'Hourly Precipitation (Bars)',
    description: 'How much rain and when',
    defaultVisible: true,
    category: 'forecast',
    required: false,
  },
  {
    id: 'precip-prob-timeline',
    name: 'Precipitation Probabiities',
    description: 'Likelihood of rain/snow',
    defaultVisible: true,
    category: 'forecast',
    required: false,
  },
  {
    id: 'dailyuv',
    name: 'Hourly EV (Bars)',
    description: 'How much ev exposure and when',
    defaultVisible: true,
    category: 'forecast',
    required: false,
  },
  {
    id: 'forecast',
    name: '7-Day Forecast',
    description: 'Weekly weather outlook',
    defaultVisible: true,
    category: 'forecast',
    required: false,
  },
  {
    id: 'airquality',
    name: 'Air Quality Index',
    description: 'Current AQI gauge and pollutant details',
    defaultVisible: true,
    category: 'weather',
    required: false,
  },
  {
    id: 'skyevents',
    name: 'Sun & Moon Events',
    description: 'Sun arc, golden hour, and moon phase tracker',
    defaultVisible: true,
    category: 'astronomy',
    required: false,
  },
  {
    id: 'daylength',
    name: 'Day Length Graph',
    description: 'Daylight in relation to the equinoxes',
    defaultVisible: true,
    category: 'astronomy',
    required: false,
  },
  {
    id: 'moontable',
    name: 'Detailed Moon Events',
    description: 'Upcoming moon events',
    defaultVisible: true,
    category: 'astronomy',
    required: false,
  },
  {
    id: 'aqitable',
    name: 'AQI Reference Table',
    description: 'Air Quality Index color codes and descriptions',
    defaultVisible: false,
    category: 'info',
    required: false,
  },
  {
    id: 'debugconsole',  
    name: 'Debug Console',
    description: 'Developer console for logging API data',
    defaultVisible: false,  
    category: 'info',
    required: false,
  },
  {
    id: 'footer',
    name: 'Footer',
    description: 'App footer with credits',
    defaultVisible: true,
    category: 'info',
    required: false,
  },
  {
    id: 'precipitation',
    name: 'Precipitation Forecast (Line)',
    description: '24-hour precipitation probability and type chart',
    defaultVisible: true,
    category: 'forecast',
    required: false,
  },
  {
    id: 'radar',
    name: 'Weather Radar',
    description: 'Government Weather Map',
    defaultVisible: true,
    category: 'forecast',
    required: false,
  },
  {
    id: 'nwsforecast',
    name: 'Forecast Highlights',
    description: 'National Weather Service Summary',
    defaultVisible: true,
    category: 'simpler',
    required: false,
  },
  {
    id: 'flu',
    name: 'Flu Trends',
    description: 'Recent Outpatient Reports',
    defaultVisible: true,
    category: 'health',
    required: false,
  },
  {
    id: 'activefires',
    name: 'Active Fires',
    description: 'Active Fires',
    defaultVisible: true,
    category: 'fire',
    required: false,
  },
  {
    id: 'firedrivers',
    name: 'Fire Drivers',
    description: 'Drivers',
    defaultVisible: true,
    category: 'fire',
    required: false,
  },
  {
    id: 'firerisk',
    name: 'Fire Risk',
    description: 'Fire Risk',
    defaultVisible: true,
    category: 'fire',
    required: false,
  },
  {
    id: 'firelinks',
    name: 'Fire Map Links',
    description: 'Fire Map Links',
    defaultVisible: true,
    category: 'fire',
    required: false,
  },
];

export const getDefaultVisibility = () => {
  const visibility = {};
  componentRegistry.forEach(comp => {
    visibility[comp.id] = comp.defaultVisible;
  });
  return visibility;
};
